---
- name: Setup k0s
  ansible.builtin.include_role:
    name: setup_k0s

- name: Write the k0s token file on controller
  template:
    src: controller-token.j2
    dest: "{{ k0s_config_dir }}/controller-token"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Create k0s controller service with install command
  register: install_controller_cmd
  command: k0s install controller --force --token-file {{ k0s_config_dir }}/controller-token
  changed_when: install_controller_cmd | length > 0

- name: Enable and check k0s service
  systemd:
    name: k0scontroller
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for k8s apiserver
  wait_for:
    host: localhost
    port: 6443
    timeout: 180
